### ISSUE TITLE
Development checklist

### ISSUE THREAD

**Issue by jsbrittain** [globaldothealth/InsightBoard#1]
**General**
- [x] Provide facility for customisation / branding options (#5 )
- [x] Add heartbeat mechanism to alert the user when the server closes (#15 )

**Upload**
- [x] Support primary key (#3 )
- [x] Enforce data types when commiting to database (#65 )
- [x] Support ACID (#56 , #60 , #63 )
- [ ] Editor diffs should be stored as such (currently the old and new frames are compared each render)

**Data**
- [ ] Tab should only read in rows that are being rendered (could be a very large dataset)

**Reports**
